name: CS-CoreLib
version: ${project.version}
author: A lot of awesome people
website: http://thebusybiscuit.github.io/

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

api-version: 1.13

commands:
  cs_triggerinterface:
    description: Background Command
    usage: Dont use it
